source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.0'

target 'sound-effector' do

end

target 'sound-effectorTests' do

end

target 'sound-effectorUITests' do

end

